export const bouquets = [
	{
		title: 'Peach Meadow',
		price: '55',
		img: 'images/peach-meadow@1x.png',
		desc: 'A soft and radiant arrangement of peach and blush roses with lush greenery in a straw basket — light and natural.',
		category: 'standart',
	},
	{
		title: 'Blush Romance',
		price: '34',
		img: 'images/blush-romance@1x.png',
		desc: 'A premium bouquet of deep pink and ivory roses, complemented by silver eucalyptus — sophisticated and intimate.',
		category: 'standart',
	},
	{
		title: 'Pastel Garden',
		price: '40',
		img: 'images/pastel-garden@1x.png',
		desc: 'A pastel-toned mix of spray roses and greenery in a woven basket — gentle, airy, and perfect for any occasion.',
		category: 'standart',
	},
	{
		title: 'Tulip Charm',
		price: '61',
		img: 'images/tulip-charm@1x.png',
		desc: 'A vivid bouquet of bright tulips and roses in a lavender box — cheerful and full of charm.',
		category: 'standart',
	},
	{
		title: 'Berry Bloom',
		price: '32',
		img: 'images/berry-bloom@1x.png',
		desc: 'A lush mix of rich pink, purple, and cream blooms with textured greens — romantic and elegant.',
		category: 'standart',
	},
	{
		title: 'Sweet Whisper',
		price: '40',
		img: 'images/sweet-whisper@1x.png',
		desc: 'A charming spring bouquet with peonies, roses, and lilac-toned accents — fresh, lively, and expressive.',
		category: 'standart',
	},
	{
		title: 'Field Joy',
		price: '49',
		img: 'images/field-joy@1x.png',
		desc: 'A rustic hand-tied bouquet of sunflowers, lisianthus, and daisies — perfect for brightening the day.',
		category: 'standart',
	},
	{
		title: 'Soft Bloom',
		price: '37',
		img: 'images/soft-bloom@1x.png',
		desc: 'A delicate bouquet of pink carnations and roses wrapped in satin paper — soft, stylish, and versatile.',
		category: 'standart',
	},
	{
		title: 'Midnight Garden',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120786.png',
		desc: 'A spellbinding bouquet of indigo delphiniums, silvery moonlit eucalyptus, and deep violet lisianthus. This enchanting arrangement evokes the mysterious beauty of a midnight garden under starlit skies.',
		category: 'top',
	},
	{
		title: 'Sunlit Italian Meadow',
		price: '62',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120787.png',
		desc: 'Capture the golden warmth of Tuscany with a radiant bouquet of sunny chamomile, vivid wild poppies, blue cornflowers, and fragrant sprigs of Italian greenery. A breath of countryside bliss.',
		category: 'top',
	},
	{
		title: 'Velvet Twilight',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120788.png',
		desc: 'A sumptuous nocturne of velvety burgundy peonies, plum dahlias, and soft blue thistle, artfully woven with dusky foliage. This bouquet evokes the allure and mystery of evening’s embrace.',
		category: 'top',
	},
	{
		title: 'Cobalt Currentse',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120790.png',
		desc: 'Ride the waves with this striking bouquet of ocean-hued hydrangeas, deep blue delphiniums, and sculptural sea holly, evoking the tranquil majesty of the open sea.',
		category: 'standart',
	},
	{
		title: 'Luminous Chartreuse',
		price: '102',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120792.png',
		desc: 'Brilliant chartreuse cymbidium orchids and gossamer hydrangea shine boldly among a sea of deep purple anemones and midnight lisianthus. An electrifying bouquet full of energy and aristocratic allure.',
		category: 'standart',
	},
	{
		title: 'Woodland Whimsy',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120793.png',
		desc: 'A magical bouquet featuring petite white spray roses, dainty waxflowers, vibrant moss, and enchanting faux mushrooms, evoking the enchanting realm of woodland sprites and secret forest clearings.',
		category: 'standart',
	},
	{
		title: 'Enchanted Lunar Landscape',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120794.png',
		desc: 'A celestial bouquet of snowy white peonies, silvery brunia, pale blue hydrangea, and shimmering eucalyptus creates a dreamscape worthy of moonlit nights and enchanted wishes.',
		category: 'standart',
	},
	{
		title: 'Monochrome Minimalism',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120795.png',
		desc: 'A striking interplay of crisp white orchids, black calla lilies, and sculptural anthurium, this bouquet transforms the essence of modern art into a bold, graphic floral statement.',
		category: 'standart',
	},
	{
		title: 'Japandi Serenity',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120796.png',
		desc: 'A tranquil composition of creamy magnolia blooms and artfully arranged linear branches, accented with soft greenery. This bouquet embodies minimalism and calm, inspired by the refined Japandi aesthetic.',
		category: 'standart',
	},
	{
		title: 'Futurist Chrome',
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120797.png',
		desc: 'A strikingly modern arrangement featuring gleaming metallic-silver leaves, electric blue anthuriums, and sculptural white orchids—evoking avant-garde elegance and the bold allure of tomorrow.',
		category: 'standart',
	},
	{
		title: 'Golden Hour',
		price: '79',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120798.png',
		desc: 'Glowing amber roses and sunlit wheat spikes mingle with soft golden ranunculus and textured grasses, capturing the warmth and glow of magic hour in an elegant, sun-kissed bouquet.',
		category: 'standart',
	},
	{
		title: 'Quiet Nostalgia',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120799.png',
		desc: 'Soft, faded pink garden roses and blush ranunculus mingle with airy sprays of lacy Queen Anne’s lace, creating a tender bouquet that gently evokes wistful, vintage memories.',
		category: 'standart',
	},
	{
		title: 'Sun-Drenched Desert',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120800.png',
		desc: 'Capture the spirit of arid elegance with ochre garden roses, sculptural succulents, and textured cacti accents, evoking endless sunbeams and the rugged beauty of the desert in bloom.',
		category: 'standart',
	},
	{
		title: 'Chinoiserie Dreams',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120801.png',
		desc: 'A graceful fusion of delicate cherry blossoms, sapphire-hued hydrangeas, and porcelain blue delphiniums evokes the timeless elegance of hand-painted chinoiserie. A bouquet brimming with artful sophistication.',
		category: 'standart',
	},
	{
		title: 'Retro Mod Bouquet',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120802.png',
		desc: 'A bold celebration of pop-art style, this bouquet features vibrant dahlias, striking graphic mums, and playful accents in electric pink, citrus orange, and lemon yellow. The ultimate statement piece.',
		category: 'top',
	},
	{
		title: 'Firelight Embrace',
		price: '102',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120803.png',
		desc: 'Rich wine-hued peonies and smoldering copper foliage unite in this luxurious bouquet, echoing the golden glow and warmth of a firelit evening. Bold, romantic, utterly captivating.',
		category: 'top',
	},
	{
		title: 'Renaissance Tapestry',
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120804.png',
		desc: 'An opulent bouquet of velvety red garden roses, burgundy peonies, and golden-hued ranunculus, elegantly wrapped with gold brocade ribbon—evoking the grandeur and artistry of a Renaissance masterpiece.',
		category: 'standart',
	},
	{
		title: 'Winter Solstice',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120805.png',
		desc: 'A luminous bouquet of icy blue hydrangeas, white roses, and silvery frosted pine, evoking the hushed elegance and shimmering calm of the longest winter night.',
		category: 'standart',
	},
	{
		title: 'Industrial Chic',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120806.png',
		desc: 'Bold steel-gray succulents meet striking rust-orange tulips, accented with silver brunia and eucalyptus. This arrangement is a modern fusion of urban edge and warm, sophisticated elegance.',
		category: 'standart',
	},
	{
		title: 'Unbridled Romance',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120807.png',
		desc: 'Lush blush garden roses entwine with fragrant, trailing jasmine in a bouquet that radiates passion and softness. Perfectly crafted to evoke a sense of timeless, heartfelt love.',
		category: 'standart',
	},
	{
		title: 'Rustic Farmhouse',
		price: '58',
		img: 'images/field-joy@1x.png',
		desc: 'Golden sunflowers, airy bluebells, and textured wheat stems are hand-tied with natural burlap ribbon, capturing the warmth and charm of a sunlit country morning.',
		category: 'standart',
	},
	{
		title: 'Stained Glass Spectrum',
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120809.png',
		desc: 'A dazzling display of vivid color blocks featuring radiant tulips, electric blue delphiniums, golden ranunculus, and bold magenta orchids—this bouquet evokes the mesmerizing artistry of stained glass windows.',
		category: 'top',
	},
	{
		title: "Painter's Muse",
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120810.png',
		desc: 'A vivid masterpiece of lush coral peonies, striking teal-tinted hydrangeas, and golden yellow ranunculus. Designed to ignite creativity, this bouquet brings the artist’s palette to life.',
		category: 'top',
	},
	{
		title: 'Moonlit Reverie',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120811.png',
		desc: 'A luminous bouquet of creamy night-blooming cereus, pale moonflowers, and silver dollar eucalyptus leaves. Evoking the tranquil poetry of midnight gardens under a gentle lunar glow.',
		category: 'standart',
	},
	{
		title: "Midsummer Night's Whimsy",
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120812.png',
		desc: 'A luminous cascade of pastel sweet peas entwined with shimmering, glow-in-the-dark foliage creates this enchanting bouquet—evoking the magical allure of a starlit midsummer evening in full bloom.',
		category: 'standart',
	},
	{
		title: 'Enchanted Forest Floor',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120813.png',
		desc: 'A whimsical bouquet evoking woodland magic, featuring velvety moss, lush ferns, delicate hellebores, tiny woodland blooms, and lifelike foraged mushrooms for a touch of enchantment.',
		category: 'standart',
	},
	{
		title: 'Espresso Elegance',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120814.png',
		desc: 'Rich, deep brown magnolias blend seamlessly with creamy lisianthus, creating a bouquet that exudes refined warmth and sophistication—perfect for those with a taste for understated luxury.',
		category: 'standart',
	},
	{
		title: 'Blueberry Sunrise',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120815.png',
		desc: 'A radiant blend of indigo hydrangeas and peach roses, accented with silvery eucalyptus. This bouquet evokes the tranquil beauty of morning light spilling over a summer berry orchard.',
		category: 'standart',
	},
	{
		title: 'Driftwood Daydream',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120816.png',
		desc: 'Sculptural driftwood branches intertwine with pristine white anemones and silvery eucalyptus, creating a mesmerizing homage to coastal elegance and the natural beauty of wind-swept shores.',
		category: 'top',
	},
	{
		title: 'Frida Kahlo Riot',
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120817.png',
		desc: "A vibrant explosion of hot pink peonies, exotic anthurium, striking fuchsia orchids, and lush tropical greens—this bouquet channels Frida's fearless artistry and unapologetic color. Unleash your inner icon.",
		category: 'top',
	},
	{
		title: 'Granite & Emerald',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120818.png',
		desc: 'A striking fusion of silvery granite-hued roses, lush emerald foliage, and vibrant chartreuse orchids. This modern bouquet evokes the elegance of stone and the vitality of a jeweled forest.',
		category: 'standart',
	},
	{
		title: 'Spring Awakening',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120819.png',
		desc: 'A fresh, elegant bouquet of pale green hellebores and pristine white tulips, evoking the first gentle blush of spring. Perfect for celebrating renewal and new beginnings.',
		category: 'standart',
	},
	{
		title: 'Cubist Abstraction',
		price: '105',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120820.png',
		desc: 'A striking bouquet of boldly structured tulips, calla lilies, and billy balls in contrasting blocks of primary colors, artfully arranged with angular foliage to echo cubist geometry. Modern artistry, reimagined in flowers.',
		category: 'standart',
	},
	{
		title: 'Dappled Sunlight',
		price: '68',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120821.png',
		desc: 'Brighten any space with lemon-hued snapdragons, crisp fresh mint, and accents of white lisianthus. This radiant bouquet evokes sunlit mornings and breezy garden strolls.',
		category: 'standart',
	},
	{
		title: 'Enchanted Library',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120822.png',
		desc: 'Step inside literary magic with fragrant French lavender, creamy white garden roses, and delicate parchment-hued lisianthus. Evocative of antique book pages and timeless stories unfolding in fragrant air.',
		category: 'standart',
	},
	{
		title: 'Surrealist Dream',
		price: '105',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120823.png',
		desc: 'A whimsical bouquet where sculptural protea, twisting calla lilies, and playful billy balls are paired with fluttering orchids and artful succulents—evoking a dreamscape of fanciful, unexpected beauty.',
		category: 'top',
	},
	{
		title: "Magpie's Hoard",
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120824.png',
		desc: 'Gleaming silver brunia, gilded eucalyptus, and iridescent anthurium petals mingle with midnight calla lilies—an opulent bouquet echoing a magpie’s love of luminous, rare treasures.',
		category: 'top',
	},
	{
		title: 'Aztec Sun',
		price: '82',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120825.png',
		desc: 'Radiant marigolds, sunlit goldenrod, and artistically painted palm leaves evoke the vibrant spirit of ancient suns. This striking bouquet blazes with warmth, energy, and bold cultural flair.',
		category: 'standart',
	},
	{
		title: 'Orchard Bounty',
		price: '82',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120826.png',
		desc: 'A lush celebration of spring, this bouquet features fragrant apple blossoms, blossoming branches with ripe crabapples, and fresh greenery—evoking a sunlit orchard at harvest. An artisanal feast for the senses.',
		category: 'standart',
	},
	{
		title: 'Pure Tranquility',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120827.png',
		desc: 'Experience calm with this all-white bouquet of lush hydrangeas, snowy roses, and elegant lisianthus, accented by sculptural ferns and velvety silver foliage. A serene blend of texture and purity.',
		category: 'standart',
	},
	{
		title: 'Desert Bloom',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120828.png',
		desc: 'An evocative bouquet of blooming cactus flowers, sandy-hued protea, and textured desert greenery. Inspired by arid landscapes, it radiates warmth, rugged elegance, and golden sunset light.',
		category: 'standart',
	},
	{
		title: 'Garden Graffiti',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120829.png',
		desc: 'A bold, avant-garde bouquet featuring vibrant spray-painted roses, neon-tipped chrysanthemums, and electric blue delphiniums—fusing lush garden blooms with edgy street-art flair for a true urban statement.',
		category: 'standart',
	},
	{
		title: 'Noble Simplicity',
		price: '70',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120830.png',
		desc: 'A striking interplay of bare dogwood branches and one exquisitely chosen white peony, celebrating restraint and elegant minimalism. Perfect for those who find beauty in purity and intention.',
		category: 'top',
	},
	{
		title: 'Tiger Lily Fever',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120831.png',
		desc: 'A bold explosion of vibrant orange tiger lilies ignites against dramatic black fern fronds, creating a striking and adventurous bouquet for those craving unapologetic color and modern edge.',
		category: 'top',
	},
	{
		title: 'Opalescent Mist',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120832.png',
		desc: "A luminous bouquet of soft pink peonies, blush lisianthus, and silver-green eucalyptus enveloped in iridescent dusty miller. Like morning dew catching the first rays of light, it's pure enchantment.",
		category: 'standart',
	},
	{
		title: 'Winter Orchard',
		price: '79',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120833.png',
		desc: 'Evoking the stark beauty of an orchard at first frost, this bouquet features sculptural bare branches, frosted white ranunculus, and clusters of icy red rosehips for a striking seasonal statement.',
		category: 'standart',
	},
	{
		title: 'Spring in Kyoto',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120834.png',
		desc: 'Experience the tranquility of cherry blossom season with airy plum blossoms and cascading violet wisteria, artfully arranged with fragrant sweet peas and soft greenery—an ode to the poetic Japanese spring.',
		category: 'standart',
	},
	{
		title: 'Jungle Fever',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120835.png',
		desc: 'Bold monstera leaves, neon green anthuriums, exotic orchids, and sculptural pincushion proteas burst with untamed energy—an electrifying bouquet inspired by the wild, playful spirit of the tropics.',
		category: 'standart',
	},
	{
		title: 'Antique Gold Nouveau',
		price: '105',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120836.png',
		desc: 'Echoing opulence and vintage charm, this bouquet weaves golden-hued roses, muted olive ranunculus, and sculptural ferns into an art nouveau-inspired masterpiece—elegant, sophisticated, and truly timeless.',
		category: 'standart',
	},
	{
		title: 'Dreamy Lullaby',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120837.png',
		desc: 'A serene composition of airy pale blue delphinium, silvery brunia, and white lisianthus evokes the tranquility of moonlit dreams—a gentle, soothing bouquet perfect for moments of calm.',
		category: 'top',
	},
	{
		title: 'Glacial Stillness',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120838.png',
		desc: 'A serene bouquet of pure white peonies, icy blue thistles, snow-hued orchids, and silvery dusty miller evokes the tranquil beauty of a frozen landscape. Immaculate, minimalist, unforgettable.',
		category: 'top',
	},
	{
		title: 'Desert Mirage',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120839.png',
		desc: 'A striking bouquet inspired by the desert’s allure, blending sandy-hued roses, golden protea, spiky blue thistle, and sculptural succulents. Earthy, exotic, and undeniably sophisticated.',
		category: 'standart',
	},
	{
		title: 'Minimal Strokes',
		price: '70',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120840.png',
		desc: 'A striking bouquet of pure white calla lilies arranged with intentional negative space and minimal greenery, evoking modern artistry through simplicity and form. Understated, elegant, and unforgettable.',
		category: 'standart',
	},
	{
		title: 'Blushing Dawn',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120841.png',
		desc: 'Awaken the senses with blushing peach tulips entwined with silvery dusty miller, evoking the tranquil glow of first light. A soft, elegant expression of new beginnings.',
		category: 'standart',
	},
	{
		title: 'Baroque Fantasy',
		price: '115',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120842.png',
		desc: 'Sumptuous gilded roses and lavish peonies intertwine with golden foliage and rich greenery, evoking the opulence of a Baroque masterpiece. An extravagant bouquet for those who desire pure luxury.',
		category: 'standart',
	},
	{
		title: 'Serene Zen',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120843.png',
		desc: 'Tranquility unfolds with white orchids nestled among smooth Zen stones and lush green moss. This harmonious arrangement evokes meditative calm and pure, natural beauty.',
		category: 'standart',
	},
	{
		title: 'Ethereal Fog',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120844.png',
		desc: 'A misty arrangement of white ranunculus, silvery dusty miller, pale eucalyptus, and soft green hellebores evokes the tranquility of dawn shrouded in gentle fog. Sublime and elegant.',
		category: 'top',
	},
	{
		title: 'Art Deco Geometry',
		price: '115',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120845.png',
		desc: 'An opulent arrangement inspired by art deco elegance, featuring sculptural gold-tipped calla lilies, crisp white orchids, and greenery arranged in striking geometric patterns. A statement of timeless luxury.',
		category: 'top',
	},
	{
		title: 'Nostalgic Sepia',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120846.png',
		desc: 'Whispering of sunlit afternoons, this vintage-inspired bouquet blends dried grasses, antique hydrangea, and preserved lunaria in warm sepia tones—a timeless embrace of elegance and memory.',
		category: 'standart',
	},
	{
		title: 'Peach Sorbet',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120847.png',
		desc: 'A luscious swirl of apricot ranunculus, peach garden roses, and creamy lisianthus, evoking the soft, sunlit sweetness of a summertime sorbet. Exquisitely fresh and utterly irresistible.',
		category: 'standart',
	},
	{
		title: 'Crimson Passion',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120848.png',
		desc: 'Sumptuous crimson roses entwined with dramatic, shadowy foliage—midnight ruscus and deep plum smokebush—create a bouquet that pulses with romance and intensity. Perfect for bold declarations of love.',
		category: 'standart',
	},
	{
		title: 'Bohemian Rhapsody',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120849.png',
		desc: 'Bursting with golden sunflowers, feathery astilbe, and wild greenery, this free-spirited bouquet channels carefree bohemia and radiant summer days with every lush, textured stem.',
		category: 'standart',
	},
	{
		title: 'Frosted Evergreen',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120850.png',
		desc: "Inspired by winter's hush, this bouquet blends lush, frosted evergreens, soft snowy cotton bolls, and shimmering silver brunia for an elegant, wintry embrace—sophisticated and serene.",
		category: 'top',
	},
	{
		title: 'Harlequin Carnival',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120851.png',
		desc: 'A bold celebration of color and texture, this bouquet fuses jewel-toned ranunculus, sapphire blue delphinium, emerald hydrangea, amethyst anemones, and textured billy balls for a festive, theatrical flourish.',
		category: 'top',
	},
	{
		title: 'Earthy Neutrals',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120852.png',
		desc: 'An artful composition of brown orchids, clay-hued roses, and textural seed pods, this bouquet celebrates nature’s subtle palette with refined elegance and organic beauty.',
		category: 'standart',
	},
	{
		title: 'Dragonfly Wings',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120853.png',
		desc: 'Glide into enchantment with shimmering iridescent orchids, pastel lisianthus, and whisper-light airy ferns—this bouquet evokes the delicate luminescence and graceful movement of a dragonfly in flight.',
		category: 'standart',
	},
	{
		title: 'Electric Citrus',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120854.png',
		desc: 'A burst of energy in floral form—vivid orange ranunculus, lime-green zinnias, and citrus-hued tulips collide in this zesty, modern arrangement that dazzles and delights the senses.',
		category: 'standart',
	},
	{
		title: 'Mist-Kissed Morning',
		price: '78',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120855.png',
		desc: 'Awaken to a tranquil bouquet of misty pale bluebells nestled among soft, pillowy moss and silvery foliage. This arrangement evokes the freshness and serenity of dawn in an enchanted woodland.',
		category: 'standart',
	},
	{
		title: 'Tropical Monsoon',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120856.png',
		desc: 'An exotic cascade of emerald palm fronds, vibrant red ginger flowers, and lush rainforest foliage. This bouquet evokes the refreshing essence of rain-soaked tropics in every stem.',
		category: 'standart',
	},
	{
		title: 'Gothic Tapestry',
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120857.png',
		desc: 'A brooding ensemble of deep black violets, midnight calla lilies, and twisted emerald vines evokes the allure of a shadowy Gothic manor—luxuriously dramatic and seductively mysterious.',
		category: 'top',
	},
	{
		title: 'Sorbet Swirl',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120858.png',
		desc: 'Indulge in a dreamy swirl of pastel ranunculus and zesty lemon-yellow stock, artfully arranged to evoke the sweetness and softness of a hand-churned sorbet. Pure confectionary elegance.',
		category: 'top',
	},
	{
		title: 'Rainforest Canopy',
		price: '110',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120859.png',
		desc: 'An exuberant display of vivid birds-of-paradise, emerald monstera leaves, and lush trailing philodendron vines. This striking bouquet evokes the vibrant energy and lushness of the tropical rainforest.',
		category: 'standart',
	},
	{
		title: 'Lavender Haze',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120860.png',
		desc: 'A misty dream of monochrome purples, featuring lush lavender, cloud-like astilbe, velvety lisianthus, and delicate scabiosa. A soothing, ethereal bouquet for lovers of all things violet.',
		category: 'standart',
	},
	{
		title: 'Blizzard Garden',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120861.png',
		desc: 'A crisp, modern bouquet of frilled white peonies, snowy lisianthus, and airy powder-blue ferns, evoking a frosted garden blanketed in gentle winter light.',
		category: 'standart',
	},
	{
		title: 'Cosmic Nebula',
		price: '105',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120862.png',
		desc: 'A mesmerizing bouquet swirling with wild violets, midnight blue delphiniums, indigo lisianthus, and accents of starry thistles—capturing the enigmatic beauty of a distant, celestial nebula.',
		category: 'standart',
	},
	{
		title: 'Misty Mountain Glen',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120863.png',
		desc: 'This serene bouquet evokes a fog-kissed woodland, blending lush evergreens, velvety white hellebores, and sprigs of silvery moss for an atmosphere of tranquil alpine beauty.',
		category: 'standart',
	},
	{
		title: 'Featherlight Touch',
		price: '58',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120864.png',
		desc: 'A whisper-soft bouquet featuring airy pampas plumes, fluffy bunny tail grass, and touches of ivory lunaria. The essence of effortless elegance for modern interiors or mindful gifting.',
		category: 'top',
	},
	{
		title: 'Caramel Dusk',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120865.png',
		desc: 'Golden toffee roses intertwine with bronze-tinted eucalyptus and velvety caramel carnations, evoking the cozy, luminous hues of a sunset fading to evening. A bouquet of soft warmth and understated luxury.',
		category: 'top',
	},
	{
		title: 'Zesty Mojito',
		price: '68',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120866.png',
		desc: 'A refreshing burst of lime-hued alstroemeria and vibrant hydrangea playfully intertwined with fragrant mint sprigs, evoking the crisp, invigorating spirit of a summer mojito.',
		category: 'standart',
	},
	{
		title: 'Modern Origami',
		price: '105',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120867.png',
		desc: 'A striking, architectural bouquet featuring crisp white calla lilies, sculpted roses, and bold angular folds of glossy aspidistra leaves—an avant-garde floral display inspired by the art of origami.',
		category: 'standart',
	},
	{
		title: 'Vintage Botanica',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120868.png',
		desc: 'Inspired by classic botanical prints, this refined bouquet blends teal thistle, sage eucalyptus, silvery brunia, and soft white garden roses—evoking timeless elegance with a painterly botanical palette.',
		category: 'standart',
	},
	{
		title: 'Violet Storm',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120869.png',
		desc: 'A moody, captivating bouquet of inky purple irises swirled with crisp white lisianthus and silver eucalyptus, evoking the energy and contrast of a gathering tempest.',
		category: 'standart',
	},
	{
		title: 'Reclaimed Romance',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120870.png',
		desc: 'Timeless beauty emerges in this bouquet of blush garden roses, dried lavender, preserved hydrangea, and sprigs of dusty herbs, delicately wrapped in antique lace for a wistful, vintage allure.',
		category: 'standart',
	},
	{
		title: 'Butterfly Migration',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120871.png',
		desc: 'A whimsical bouquet inspired by nature’s migrations, featuring airy blue delphinium, fluttering wildflowers, and sprigs of larkspur—evoking the delicate dance of butterflies on a summer breeze.',
		category: 'top',
	},
	{
		title: 'Tidal Pool Wonder',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120872.png',
		desc: 'Evoking the mysterious beauty of the ocean, this bouquet features sea-green succulents, striking blue thistles, and hints of silvery eucalyptus—an aquatic-inspired marvel for lovers of the extraordinary.',
		category: 'top',
	},
	{
		title: 'Lunar Eclipse',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120873.png',
		desc: 'A striking interplay of charcoal-hued scabiosa and ghostly white lilies, shadowed with midnight delphinium and dusky foliage—a bouquet evoking cosmic mystery and nocturnal elegance.',
		category: 'standart',
	},
	{
		title: 'Victorian Secret Garden',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120874.png',
		desc: 'Step into a hidden world with lush garden roses in soft mauves, lilac sweet peas, and heirloom greenery. This bouquet evokes the romance of a forgotten, flower-filled sanctuary.',
		category: 'standart',
	},
	{
		title: 'Starry Night',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120875.png',
		desc: 'A celestial-inspired bouquet featuring deep navy delphiniums, velvety indigo anemones, and playful yellow craspedia orbs. This arrangement evokes the magic of a starlit sky.',
		category: 'standart',
	},
	{
		title: 'Monochrome Crimson',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120876.png',
		desc: 'A sultry fusion of scarlet lilies, crimson berries, and deep, dark foliage evokes a mood of unapologetic elegance. This monochrome bouquet is dramatic, modern, and utterly captivating.',
		category: 'standart',
	},
	{
		title: 'Coral Reef',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120877.png',
		desc: 'Dive into a vivid palette of electric blue delphiniums, vibrant orange ranunculus, and textured anemones—an undersea-inspired bouquet radiating energy, movement, and brilliant color contrasts.',
		category: 'top',
	},
	{
		title: 'Fire & Ice',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120878.png',
		desc: 'Striking red leucadendrons blaze against a backdrop of icy blue eucalyptus, creating a dramatic contrast of heat and chill—modern, sculptural, and unforgettable for those who love bold statements.',
		category: 'top',
	},
	{
		title: 'Pagoda Tranquility',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120879.png',
		desc: 'Serene branches of pale cherry blossoms mingle with elegant stems of slender bamboo, evoking the calm of an oriental garden retreat. A graceful tribute to peace and natural beauty.',
		category: 'standart',
	},
	{
		title: 'Emerald City',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120880.png',
		desc: 'A striking composition of vivid green viburnum, sculpted aspidistra leaves, and bold tulips in jewel tones. Modern structure and lush color evoke the vibrance of an urban oasis.',
		category: 'standart',
	},
	{
		title: 'Shabby Chic Nostalgia',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120881.png',
		desc: 'Soft blush garden roses and feathery astilbe rest in a charming vintage blue jar, accented with lacy baby’s breath and silvery eucalyptus for a romantic, wistful touch of bygone elegance.',
		category: 'standart',
	},
	{
		title: 'Enchanted Dusk',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120882.png',
		desc: "A moody bouquet blending twilight-hued lisianthus, amethyst roses, velvety clematis, and plumes of smoke bush. Lush purples and silvery foliage evoke the magic of evening's embrace.",
		category: 'standart',
	},
	{
		title: 'Nordic Frost',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120883.png',
		desc: 'A wintry composition of aromatic pine, icy white hydrangea tinged with blue, and pale blush roses evokes the tranquil elegance of a Scandinavian landscape after fresh snowfall.',
		category: 'standart',
	},
	{
		title: 'Pocket Prairie',
		price: '58',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120884.png',
		desc: 'A delightfully rustic bouquet featuring wisps of native grasses, sprigs of yarrow, dainty asters, and petite wildflowers. Evokes the quiet wonder of a wild prairie in miniature form.',
		category: 'top',
	},
	{
		title: 'Celestial Halo',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120885.png',
		desc: "Radiant golden mimosa forms a luminous centerpiece, encircled by airy clouds of baby's breath—an ethereal bouquet capturing the serenity and wonder of a starlit sky.",
		category: 'top',
	},
	{
		title: 'Wuthering Winds',
		price: '72',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120886.png',
		desc: 'Evoking untamed moors, this windswept bouquet features wild grasses, feathery pampas, silver-green eucalyptus, and windswept white lisianthus, beautifully arranged for a sense of organic, natural movement.',
		category: 'standart',
	},
	{
		title: 'Espresso Noir',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120887.png',
		desc: 'A sultry arrangement blending deep chocolate cosmos, velvety scabiosa, and lush emerald greens. Moody, artful, and decadent—perfect for lovers of bold florals and refined drama.',
		category: 'standart',
	},
	{
		title: 'Flamingo Parade',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120888.png',
		desc: 'A jubilant burst of pink featuring exuberant flamingo-hued peonies, fluffy astilbe, feathery pampas grass, and playful carnations. An irresistibly soft, vibrant bouquet that celebrates whimsy and bold color.',
		category: 'standart',
	},
	{
		title: 'Café au Lait',
		price: '89',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120889.png',
		desc: 'Indulge in sophistication with luscious café au lait dahlias and caramel-hued ranunculus, artfully accented by soft blush roses and feathery greenery. The essence of creamy elegance in every stem.',
		category: 'standart',
	},
	{
		title: 'Artisan Tapestry',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120890.png',
		desc: 'A textured masterpiece blending woven reeds, dried lavender, and luxurious silk blooms—each stem hand-crafted to evoke the beauty of a timeless textile, perfect for the discerning aesthete.',
		category: 'top',
	},
	{
		title: 'Berry Orchard',
		price: '98',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120891.png',
		desc: 'A lavish bouquet bursting with jewel-toned ranunculus, rich raspberry-hued foliage, and accents of blackberry scabiosa—evoking the lush abundance of a sun-drenched orchard at harvest.',
		category: 'top',
	},
	{
		title: 'Chromatic Chaos',
		price: '92',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120892.png',
		desc: 'A jubilant explosion of multicolored wildflowers—delphinium, poppies, daisies, and asters—boldly styled in unruly abundance. This maximalist bouquet is pure, joyful vibrancy designed to wow.',
		category: 'standart',
	},
	{
		title: 'Hushed Morning Dew',
		price: '68',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120893.png',
		desc: 'A tranquil bouquet featuring petite white lisianthus buds, snowdrops, and soft green hellebores, evoking the freshness and serenity of dawn kissed by gentle dew.',
		category: 'standart',
	},
	{
		title: 'Forest Nymph',
		price: '88',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120894.png',
		desc: 'Whispering woodland magic, this bouquet entwines hidden violets, feathered ferns, and lush spirals of emerald moss, evoking the secretive beauty of an enchanted glade.',
		category: 'standart',
	},
	{
		title: 'Scented Memoir',
		price: '73',
		img: 'https://ftp.goit.study/img/flowers/68498236a1003120895.png',
		desc: 'Delicate pale anemones mingle with fragrant sprigs of rosemary, thyme, and lavender in this poetic bouquet—evoking nostalgia and the gentle elegance of an herb-scented garden.',
		category: 'standart',
	},
];

export async function seedBouquets(prisma) {
	await prisma.product.createMany({ data: bouquets });
	return bouquets.length;
}
